# This workflow will upload a Python Package using Twine when a release is created

name: pypi-publish
description: GitHub action to publish python packages to Pypi repository
outputs: { }

# Controls when the workflow will run
runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
      shell: bash
    - name: Create packages
      run: python -m build
      shell: bash
    - name: Run twine check
      run: twine check dist/*
      shell: bash
    - name: Upload to pypi
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USER }}
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: twine upload dist/*.whl
      shell: bash
