# This workflow will upload a Python Package using Twine when a release is created

name: pypi-publish
description: GitHub action to upload Python distribution packages to PyPI
inputs:
  user:
    description: PyPI user
    required: false
    default: ${{ secrets.PYPI_USER }} || __token__
  token:
    description: Password for your PyPI user or an access token
    required: false
    default: ${{ secrets.PYPI_TOKEN }} || exit 1
  dry-run:
    description: Upload distributions to TestPyPI
    required: false
    default: 'false'
  repository-url:
    description: The repository URL to use
    required: false
    default: https://upload.pypi.org/legacy/
  packages-dir:
    description: The target directory for distribution
    required: false
    default: dist
  verify-metadata:
    description: Check metadata before uploading
    required: false
    default: 'true'
  skip-existing:
    description: >-
      Do not fail if a Python package distribution
      exists in the target package index
    required: false
    default: 'false'
  verbose:
    description: Show verbose output.
    required: false
    default: 'false'
  print-hash:
    description: Show hash values of files to be uploaded
    required: false
    default: 'false'
branding:
  color: orange
  icon: upload-cloud

# Controls when the workflow will run
runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Arguments
      run: |
        TWINE_EXTRA_ARGS=--disable-progress-bar
        if [[ ${{ inputs.skip-existing }} != "false" ]] ; then
          TWINE_EXTRA_ARGS="${TWINE_EXTRA_ARGS} --skip-existing"
        fi
        if [[ ${{ inputs.verbose }} != "false" ]] ; then
          TWINE_EXTRA_ARGS="--verbose $TWINE_EXTRA_ARGS"
        fi
        echo "TWINE_EXTRA_ARGS=$TWINE_EXTRA_ARGS" >> $GITHUB_ENV

        # todo: check if altering inputs work
        if [[ ${{ inputs.dry-run }} != "false" ]] ; then
          ${{ inputs.token }}=${{ secrets.PYPI_TEST_TOKEN }} || exit 1
          ${{ inputs.repository-url }}=https://test.pypi.org/simple/
        fi
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
      shell: bash

    - name: Create packages
      run: python -m build
      shell: bash

    - name: Run twine check
      if: ${{ inputs.verify-metadata }}
      run: twine check ${{ inputs.packages-dir }}/*
      shell: bash

    - name: Print hash
      # todo: verify shell behavior on windows OS
      if: inputs.print-hash != false || inputs.verbose != false
      run: python print_hash.py ${{ inputs.packages-dir }}
      shell: bash

    - name: Upload to pypi
      env:
        TWINE_USERNAME: ${{ inputs.user }}
        TWINE_PASSWORD: ${{ inputs.token }}
        TWINE_REPOSITORY_URL: ${{ inputs.repository-url }}
      run: twine upload ${{ env.TWINE_EXTRA_ARGS }} ${{ inputs.packages-dir }}/*.whl
      shell: bash
